# DataSource Config
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://39.102.58.35:3306/longganghe?useUnicode=true&characterEncoding=UTF-8&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: jsjs=123

server:
  port: 8082

#mybatis-plus:
#  mapper-locations: classpath*:com/example/demo/mapper/xml/*Mapper.xml
#  global-config:
#    banner: false
